Vagrant.configure(2) do |config|
  config.ssh.pty = true

# nodo 1 
  config.vm.define 'nodo1' do |nodo1|  
    nodo1.vm.box = "centos7"
    nodo1.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', 1048]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    nodo1.vm.provision "shell", inline: <<-SHELL
      yum list
      yum -y install puppet
    SHELL
    #nodo1.vm.provision :puppet do |puppet|
    #  puppet.manifest_file  = 'Puppet_oracle12c.pp'
    #end
  end
end
